name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.4']

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml, fileinfo
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Lint
        run: composer lint

      - name: PHPStan
        run: composer analyse

      - name: Tests
        run: composer test

      - name: Security audit
        run: composer security-audit
